// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/chat_message_model.dart';
import 'data/models/chat_session_model.dart';
import 'data/models/flashcard_deck_model.dart';
import 'data/models/flashcard_model.dart';
import 'data/models/flashcard_review_model.dart';
import 'data/models/highlight_model.dart';
import 'data/models/note_annotation_model.dart';
import 'data/models/note_chunk_model.dart';
import 'data/models/note_model.dart';
import 'data/models/notebook_model.dart';
import 'data/models/quiz_attempt_model.dart';
import 'data/models/quiz_model.dart';
import 'data/models/quiz_question_model.dart';
import 'data/models/study_plan_model.dart';
import 'data/models/study_session_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1046454580701227023),
    name: 'ChatMessageModel',
    lastPropertyId: const obx_int.IdUid(7, 1461084510288695497),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7269846942866543983),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5480286061346078278),
        name: 'sessionId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8884856767995537327),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1203525895428921182),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5288636324990732128),
        name: 'sourceChunksJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2770223527905720367),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1461084510288695497),
        name: 'sourceChunks',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4506380483333451149),
    name: 'ChatSessionModel',
    lastPropertyId: const obx_int.IdUid(5, 9197382391278356048),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 165514007843395364),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2204005737498409064),
        name: 'notebookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3705874362717506980),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4592568024335396645),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9197382391278356048),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9032768762954709459),
    name: 'NoteChunkModel',
    lastPropertyId: const obx_int.IdUid(5, 1236417375188136629),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5189973311244807839),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7248010236840886044),
        name: 'noteId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1837519579036404184),
        name: 'text',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1314234798251966888),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7039298164604881050),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1236417375188136629),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7564743392253910987),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 639880327650542879),
    name: 'NoteModel',
    lastPropertyId: const obx_int.IdUid(11, 7074739352079450105),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7493085967903969016),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1868132970632316320),
        name: 'notebookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6791199383758685987),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3436965771167809852),
        name: 'rawText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2307671590052900693),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3048807630202647373),
        name: 'statusStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3294796909752148260),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5976698569142599888),
        name: 'sourcePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7332125394709273695),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8594773664290871228),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7074739352079450105),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3792066214926863363),
    name: 'NotebookModel',
    lastPropertyId: const obx_int.IdUid(6, 1033064756244229920),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6252830764123975353),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7642281792414701993),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5183090306782685205),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5709763527111767446),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1078540705443708204),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1033064756244229920),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6451964896982366558),
    name: 'QuizAttemptModel',
    lastPropertyId: const obx_int.IdUid(6, 2270742427004128167),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 499659321504218885),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1522018494050414439),
        name: 'quizId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3858997276387733012),
        name: 'score',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7864383946641971957),
        name: 'totalQuestions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3883116116647917663),
        name: 'answersJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2270742427004128167),
        name: 'completedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2613755880110159420),
    name: 'QuizModel',
    lastPropertyId: const obx_int.IdUid(7, 5808929008602838097),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8202699155566821790),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6955556649583548946),
        name: 'notebookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5852971750928200079),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 647950322455089973),
        name: 'questionTypeStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7182485958758857843),
        name: 'difficultyStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8064498048448315317),
        name: 'questionCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5808929008602838097),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1482522122888257152),
    name: 'QuizQuestionModel',
    lastPropertyId: const obx_int.IdUid(10, 7781981202367255723),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 778325170771372026),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8184095909635359991),
        name: 'quizId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5907645397759051058),
        name: 'question',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4266084967757572510),
        name: 'typeStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1413746279355004286),
        name: 'optionsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8961549752986946674),
        name: 'correctAnswer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4885319488533208031),
        name: 'explanation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5790499054851937342),
        name: 'questionIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2060906784426041782),
        name: 'options',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7781981202367255723),
        name: 'topic',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 1906718705784843136),
    name: 'FlashcardDeckModel',
    lastPropertyId: const obx_int.IdUid(5, 2931307739449691286),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2737294394150503228),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8527718805122512438),
        name: 'notebookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1901385270206931046),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2265792436383260131),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2931307739449691286),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 8021950451290291198),
    name: 'FlashcardModel',
    lastPropertyId: const obx_int.IdUid(10, 499091264113230882),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5110773408333550866),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2749739035210644801),
        name: 'deckId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9127609029203608839),
        name: 'front',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2699959230240147113),
        name: 'back',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1544395815050676169),
        name: 'cardIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6088320542144454268),
        name: 'easeFactor',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3079107636840857426),
        name: 'interval',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7938750268313951294),
        name: 'repetitions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6697827443456448538),
        name: 'nextReviewAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 499091264113230882),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4042082394175325421),
    name: 'FlashcardReviewModel',
    lastPropertyId: const obx_int.IdUid(4, 9207873289050991607),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7884822772138633424),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8759165236374270513),
        name: 'flashcardId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3654747303238874965),
        name: 'quality',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9207873289050991607),
        name: 'reviewedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 4764562703473078731),
    name: 'StudyPlanModel',
    lastPropertyId: const obx_int.IdUid(4, 5510359818244762691),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 410819503669801249),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2722188561551204306),
        name: 'date',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8275736587803804405),
        name: 'tasksJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5510359818244762691),
        name: 'generatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 5716520234659994830),
    name: 'StudySessionModel',
    lastPropertyId: const obx_int.IdUid(6, 4356166879606915250),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4830934544339385600),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8364070969710480068),
        name: 'notebookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2737360093686045992),
        name: 'activityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 927608042510842869),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1831867686028808862),
        name: 'startedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4356166879606915250),
        name: 'endedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 3468003717060621635),
    name: 'HighlightModel',
    lastPropertyId: const obx_int.IdUid(7, 498284965081390234),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2420376006543883270),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2718575265295425823),
        name: 'noteId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2893578593073899308),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 75323981526552292),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2710336522799967249),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7922856430410494492),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 498284965081390234),
        name: 'aiAnswer',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 450434228047843849),
    name: 'NoteAnnotationModel',
    lastPropertyId: const obx_int.IdUid(5, 395825897580400365),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1793606875551891962),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2062825509426237305),
        name: 'noteId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2470032409116588621),
        name: 'strokesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6873530999209517945),
        name: 'sidenotesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 395825897580400365),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(15, 450434228047843849),
    lastIndexId: const obx_int.IdUid(2, 7564743392253910987),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessageModel: obx_int.EntityDefinition<ChatMessageModel>(
      model: _entities[0],
      toOneRelations: (ChatMessageModel object) => [],
      toManyRelations: (ChatMessageModel object) => {},
      getId: (ChatMessageModel object) => object.id,
      setId: (ChatMessageModel object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageModel object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final sourceChunksJsonOffset = object.sourceChunksJson == null
            ? null
            : fbb.writeString(object.sourceChunksJson!);
        final sourceChunksOffset = object.sourceChunks == null
            ? null
            : fbb.writeList(
                object.sourceChunks!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sessionId);
        fbb.addOffset(2, contentOffset);
        fbb.addBool(3, object.isUser);
        fbb.addOffset(4, sourceChunksJsonOffset);
        fbb.addInt64(5, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addOffset(6, sourceChunksOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sessionIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isUserParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final sourceChunksJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
        );
        final object =
            ChatMessageModel(
                id: idParam,
                sessionId: sessionIdParam,
                content: contentParam,
                isUser: isUserParam,
                sourceChunksJson: sourceChunksJsonParam,
                createdAt: createdAtParam,
              )
              ..sourceChunks = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGetNullable(buffer, rootOffset, 16);

        return object;
      },
    ),
    ChatSessionModel: obx_int.EntityDefinition<ChatSessionModel>(
      model: _entities[1],
      toOneRelations: (ChatSessionModel object) => [],
      toManyRelations: (ChatSessionModel object) => {},
      getId: (ChatSessionModel object) => object.id,
      setId: (ChatSessionModel object, int id) {
        object.id = id;
      },
      objectToFB: (ChatSessionModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notebookId);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(4, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notebookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
        );
        final object = ChatSessionModel(
          id: idParam,
          notebookId: notebookIdParam,
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    NoteChunkModel: obx_int.EntityDefinition<NoteChunkModel>(
      model: _entities[2],
      toOneRelations: (NoteChunkModel object) => [],
      toManyRelations: (NoteChunkModel object) => {},
      getId: (NoteChunkModel object) => object.id,
      setId: (NoteChunkModel object, int id) {
        object.id = id;
      },
      objectToFB: (NoteChunkModel object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.noteId);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.chunkIndex);
        fbb.addOffset(4, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final embeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 12);
        final object = NoteChunkModel(
          id: idParam,
          noteId: noteIdParam,
          text: textParam,
          chunkIndex: chunkIndexParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    NoteModel: obx_int.EntityDefinition<NoteModel>(
      model: _entities[3],
      toOneRelations: (NoteModel object) => [],
      toManyRelations: (NoteModel object) => {},
      getId: (NoteModel object) => object.id,
      setId: (NoteModel object, int id) {
        object.id = id;
      },
      objectToFB: (NoteModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final rawTextOffset = fbb.writeString(object.rawText);
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        final statusStrOffset = fbb.writeString(object.statusStr);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final sourcePathOffset = object.sourcePath == null
            ? null
            : fbb.writeString(object.sourcePath!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notebookId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, rawTextOffset);
        fbb.addOffset(4, summaryOffset);
        fbb.addOffset(5, statusStrOffset);
        fbb.addOffset(6, sourceTypeOffset);
        fbb.addOffset(7, sourcePathOffset);
        fbb.addInt64(8, object.chunkCount);
        fbb.addInt64(9, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(10, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notebookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final rawTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final statusStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final sourcePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0) / 1000)
              .round(),
        );
        final object = NoteModel(
          id: idParam,
          notebookId: notebookIdParam,
          title: titleParam,
          rawText: rawTextParam,
          summary: summaryParam,
          statusStr: statusStrParam,
          sourceType: sourceTypeParam,
          sourcePath: sourcePathParam,
          chunkCount: chunkCountParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    NotebookModel: obx_int.EntityDefinition<NotebookModel>(
      model: _entities[4],
      toOneRelations: (NotebookModel object) => [],
      toManyRelations: (NotebookModel object) => {},
      getId: (NotebookModel object) => object.id,
      setId: (NotebookModel object, int id) {
        object.id = id;
      },
      objectToFB: (NotebookModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, colorOffset);
        fbb.addInt64(4, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(5, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final colorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
        );
        final object = NotebookModel(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          color: colorParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    QuizAttemptModel: obx_int.EntityDefinition<QuizAttemptModel>(
      model: _entities[5],
      toOneRelations: (QuizAttemptModel object) => [],
      toManyRelations: (QuizAttemptModel object) => {},
      getId: (QuizAttemptModel object) => object.id,
      setId: (QuizAttemptModel object, int id) {
        object.id = id;
      },
      objectToFB: (QuizAttemptModel object, fb.Builder fbb) {
        final answersJsonOffset = fbb.writeString(object.answersJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quizId);
        fbb.addInt64(2, object.score);
        fbb.addInt64(3, object.totalQuestions);
        fbb.addOffset(4, answersJsonOffset);
        fbb.addInt64(5, object.completedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final quizIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final scoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final totalQuestionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final answersJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final completedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
        );
        final object = QuizAttemptModel(
          id: idParam,
          quizId: quizIdParam,
          score: scoreParam,
          totalQuestions: totalQuestionsParam,
          answersJson: answersJsonParam,
          completedAt: completedAtParam,
        );

        return object;
      },
    ),
    QuizModel: obx_int.EntityDefinition<QuizModel>(
      model: _entities[6],
      toOneRelations: (QuizModel object) => [],
      toManyRelations: (QuizModel object) => {},
      getId: (QuizModel object) => object.id,
      setId: (QuizModel object, int id) {
        object.id = id;
      },
      objectToFB: (QuizModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final questionTypeStrOffset = fbb.writeString(object.questionTypeStr);
        final difficultyStrOffset = fbb.writeString(object.difficultyStr);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notebookId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, questionTypeStrOffset);
        fbb.addOffset(4, difficultyStrOffset);
        fbb.addInt64(5, object.questionCount);
        fbb.addInt64(6, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notebookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final questionTypeStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final difficultyStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final questionCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
        );
        final object = QuizModel(
          id: idParam,
          notebookId: notebookIdParam,
          title: titleParam,
          questionTypeStr: questionTypeStrParam,
          difficultyStr: difficultyStrParam,
          questionCount: questionCountParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    QuizQuestionModel: obx_int.EntityDefinition<QuizQuestionModel>(
      model: _entities[7],
      toOneRelations: (QuizQuestionModel object) => [],
      toManyRelations: (QuizQuestionModel object) => {},
      getId: (QuizQuestionModel object) => object.id,
      setId: (QuizQuestionModel object, int id) {
        object.id = id;
      },
      objectToFB: (QuizQuestionModel object, fb.Builder fbb) {
        final questionOffset = fbb.writeString(object.question);
        final typeStrOffset = fbb.writeString(object.typeStr);
        final optionsJsonOffset = fbb.writeString(object.optionsJson);
        final correctAnswerOffset = fbb.writeString(object.correctAnswer);
        final explanationOffset = object.explanation == null
            ? null
            : fbb.writeString(object.explanation!);
        final optionsOffset = fbb.writeList(
          object.options.map(fbb.writeString).toList(growable: false),
        );
        final topicOffset = object.topic == null
            ? null
            : fbb.writeString(object.topic!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quizId);
        fbb.addOffset(2, questionOffset);
        fbb.addOffset(3, typeStrOffset);
        fbb.addOffset(4, optionsJsonOffset);
        fbb.addOffset(5, correctAnswerOffset);
        fbb.addOffset(6, explanationOffset);
        fbb.addInt64(7, object.questionIndex);
        fbb.addOffset(8, optionsOffset);
        fbb.addOffset(9, topicOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final quizIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final questionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final optionsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final correctAnswerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final explanationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final questionIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final topicParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object =
            QuizQuestionModel(
                id: idParam,
                quizId: quizIdParam,
                question: questionParam,
                typeStr: typeStrParam,
                optionsJson: optionsJsonParam,
                correctAnswer: correctAnswerParam,
                explanation: explanationParam,
                questionIndex: questionIndexParam,
                topic: topicParam,
              )
              ..options = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 20, []);

        return object;
      },
    ),
    FlashcardDeckModel: obx_int.EntityDefinition<FlashcardDeckModel>(
      model: _entities[8],
      toOneRelations: (FlashcardDeckModel object) => [],
      toManyRelations: (FlashcardDeckModel object) => {},
      getId: (FlashcardDeckModel object) => object.id,
      setId: (FlashcardDeckModel object, int id) {
        object.id = id;
      },
      objectToFB: (FlashcardDeckModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notebookId);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(4, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notebookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
        );
        final object = FlashcardDeckModel(
          id: idParam,
          notebookId: notebookIdParam,
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    FlashcardModel: obx_int.EntityDefinition<FlashcardModel>(
      model: _entities[9],
      toOneRelations: (FlashcardModel object) => [],
      toManyRelations: (FlashcardModel object) => {},
      getId: (FlashcardModel object) => object.id,
      setId: (FlashcardModel object, int id) {
        object.id = id;
      },
      objectToFB: (FlashcardModel object, fb.Builder fbb) {
        final frontOffset = fbb.writeString(object.front);
        final backOffset = fbb.writeString(object.back);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.deckId);
        fbb.addOffset(2, frontOffset);
        fbb.addOffset(3, backOffset);
        fbb.addInt64(4, object.cardIndex);
        fbb.addFloat64(5, object.easeFactor);
        fbb.addInt64(6, object.interval);
        fbb.addInt64(7, object.repetitions);
        fbb.addInt64(
          8,
          object.nextReviewAt == null
              ? null
              : object.nextReviewAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.addInt64(9, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nextReviewAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deckIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final frontParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final backParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final cardIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final easeFactorParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final intervalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final repetitionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final nextReviewAtParam = nextReviewAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (nextReviewAtValue / 1000).round(),
              );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0) / 1000)
              .round(),
        );
        final object = FlashcardModel(
          id: idParam,
          deckId: deckIdParam,
          front: frontParam,
          back: backParam,
          cardIndex: cardIndexParam,
          easeFactor: easeFactorParam,
          interval: intervalParam,
          repetitions: repetitionsParam,
          nextReviewAt: nextReviewAtParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    FlashcardReviewModel: obx_int.EntityDefinition<FlashcardReviewModel>(
      model: _entities[10],
      toOneRelations: (FlashcardReviewModel object) => [],
      toManyRelations: (FlashcardReviewModel object) => {},
      getId: (FlashcardReviewModel object) => object.id,
      setId: (FlashcardReviewModel object, int id) {
        object.id = id;
      },
      objectToFB: (FlashcardReviewModel object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.flashcardId);
        fbb.addInt64(2, object.quality);
        fbb.addInt64(3, object.reviewedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final flashcardIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final qualityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final reviewedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
        );
        final object = FlashcardReviewModel(
          id: idParam,
          flashcardId: flashcardIdParam,
          quality: qualityParam,
          reviewedAt: reviewedAtParam,
        );

        return object;
      },
    ),
    StudyPlanModel: obx_int.EntityDefinition<StudyPlanModel>(
      model: _entities[11],
      toOneRelations: (StudyPlanModel object) => [],
      toManyRelations: (StudyPlanModel object) => {},
      getId: (StudyPlanModel object) => object.id,
      setId: (StudyPlanModel object, int id) {
        object.id = id;
      },
      objectToFB: (StudyPlanModel object, fb.Builder fbb) {
        final tasksJsonOffset = fbb.writeString(object.tasksJson);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.microsecondsSinceEpoch * 1000);
        fbb.addOffset(2, tasksJsonOffset);
        fbb.addInt64(3, object.generatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dateParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0) / 1000)
              .round(),
        );
        final tasksJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final generatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
        );
        final object = StudyPlanModel(
          id: idParam,
          date: dateParam,
          tasksJson: tasksJsonParam,
          generatedAt: generatedAtParam,
        );

        return object;
      },
    ),
    StudySessionModel: obx_int.EntityDefinition<StudySessionModel>(
      model: _entities[12],
      toOneRelations: (StudySessionModel object) => [],
      toManyRelations: (StudySessionModel object) => {},
      getId: (StudySessionModel object) => object.id,
      setId: (StudySessionModel object, int id) {
        object.id = id;
      },
      objectToFB: (StudySessionModel object, fb.Builder fbb) {
        final activityTypeOffset = fbb.writeString(object.activityType);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notebookId);
        fbb.addOffset(2, activityTypeOffset);
        fbb.addInt64(3, object.durationSeconds);
        fbb.addInt64(4, object.startedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(5, object.endedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notebookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final activityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final startedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
        );
        final endedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
        );
        final object = StudySessionModel(
          id: idParam,
          notebookId: notebookIdParam,
          activityType: activityTypeParam,
          durationSeconds: durationSecondsParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
        );

        return object;
      },
    ),
    HighlightModel: obx_int.EntityDefinition<HighlightModel>(
      model: _entities[13],
      toOneRelations: (HighlightModel object) => [],
      toManyRelations: (HighlightModel object) => {},
      getId: (HighlightModel object) => object.id,
      setId: (HighlightModel object, int id) {
        object.id = id;
      },
      objectToFB: (HighlightModel object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final aiAnswerOffset = object.aiAnswer == null
            ? null
            : fbb.writeString(object.aiAnswer!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.noteId);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.colorValue);
        fbb.addOffset(4, noteOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, aiAnswerOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final aiAnswerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = HighlightModel(
          id: idParam,
          noteId: noteIdParam,
          text: textParam,
          colorValue: colorValueParam,
          note: noteParam,
          aiAnswer: aiAnswerParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    NoteAnnotationModel: obx_int.EntityDefinition<NoteAnnotationModel>(
      model: _entities[14],
      toOneRelations: (NoteAnnotationModel object) => [],
      toManyRelations: (NoteAnnotationModel object) => {},
      getId: (NoteAnnotationModel object) => object.id,
      setId: (NoteAnnotationModel object, int id) {
        object.id = id;
      },
      objectToFB: (NoteAnnotationModel object, fb.Builder fbb) {
        final strokesJsonOffset = fbb.writeString(object.strokesJson);
        final sidenotesJsonOffset = fbb.writeString(object.sidenotesJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.noteId);
        fbb.addOffset(2, strokesJsonOffset);
        fbb.addOffset(3, sidenotesJsonOffset);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final strokesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sidenotesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = NoteAnnotationModel(
          id: idParam,
          noteId: noteIdParam,
          strokesJson: strokesJsonParam,
          sidenotesJson: sidenotesJsonParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessageModel] entity fields to define ObjectBox queries.
class ChatMessageModel_ {
  /// See [ChatMessageModel.id].
  static final id = obx.QueryIntegerProperty<ChatMessageModel>(
    _entities[0].properties[0],
  );

  /// See [ChatMessageModel.sessionId].
  static final sessionId = obx.QueryIntegerProperty<ChatMessageModel>(
    _entities[0].properties[1],
  );

  /// See [ChatMessageModel.content].
  static final content = obx.QueryStringProperty<ChatMessageModel>(
    _entities[0].properties[2],
  );

  /// See [ChatMessageModel.isUser].
  static final isUser = obx.QueryBooleanProperty<ChatMessageModel>(
    _entities[0].properties[3],
  );

  /// See [ChatMessageModel.sourceChunksJson].
  static final sourceChunksJson = obx.QueryStringProperty<ChatMessageModel>(
    _entities[0].properties[4],
  );

  /// See [ChatMessageModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<ChatMessageModel>(
    _entities[0].properties[5],
  );

  /// See [ChatMessageModel.sourceChunks].
  static final sourceChunks = obx.QueryStringVectorProperty<ChatMessageModel>(
    _entities[0].properties[6],
  );
}

/// [ChatSessionModel] entity fields to define ObjectBox queries.
class ChatSessionModel_ {
  /// See [ChatSessionModel.id].
  static final id = obx.QueryIntegerProperty<ChatSessionModel>(
    _entities[1].properties[0],
  );

  /// See [ChatSessionModel.notebookId].
  static final notebookId = obx.QueryIntegerProperty<ChatSessionModel>(
    _entities[1].properties[1],
  );

  /// See [ChatSessionModel.title].
  static final title = obx.QueryStringProperty<ChatSessionModel>(
    _entities[1].properties[2],
  );

  /// See [ChatSessionModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<ChatSessionModel>(
    _entities[1].properties[3],
  );

  /// See [ChatSessionModel.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<ChatSessionModel>(
    _entities[1].properties[4],
  );
}

/// [NoteChunkModel] entity fields to define ObjectBox queries.
class NoteChunkModel_ {
  /// See [NoteChunkModel.id].
  static final id = obx.QueryIntegerProperty<NoteChunkModel>(
    _entities[2].properties[0],
  );

  /// See [NoteChunkModel.noteId].
  static final noteId = obx.QueryIntegerProperty<NoteChunkModel>(
    _entities[2].properties[1],
  );

  /// See [NoteChunkModel.text].
  static final text = obx.QueryStringProperty<NoteChunkModel>(
    _entities[2].properties[2],
  );

  /// See [NoteChunkModel.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<NoteChunkModel>(
    _entities[2].properties[3],
  );

  /// See [NoteChunkModel.embedding].
  static final embedding = obx.QueryHnswProperty<NoteChunkModel>(
    _entities[2].properties[4],
  );
}

/// [NoteModel] entity fields to define ObjectBox queries.
class NoteModel_ {
  /// See [NoteModel.id].
  static final id = obx.QueryIntegerProperty<NoteModel>(
    _entities[3].properties[0],
  );

  /// See [NoteModel.notebookId].
  static final notebookId = obx.QueryIntegerProperty<NoteModel>(
    _entities[3].properties[1],
  );

  /// See [NoteModel.title].
  static final title = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[2],
  );

  /// See [NoteModel.rawText].
  static final rawText = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[3],
  );

  /// See [NoteModel.summary].
  static final summary = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[4],
  );

  /// See [NoteModel.statusStr].
  static final statusStr = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[5],
  );

  /// See [NoteModel.sourceType].
  static final sourceType = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[6],
  );

  /// See [NoteModel.sourcePath].
  static final sourcePath = obx.QueryStringProperty<NoteModel>(
    _entities[3].properties[7],
  );

  /// See [NoteModel.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<NoteModel>(
    _entities[3].properties[8],
  );

  /// See [NoteModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<NoteModel>(
    _entities[3].properties[9],
  );

  /// See [NoteModel.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<NoteModel>(
    _entities[3].properties[10],
  );
}

/// [NotebookModel] entity fields to define ObjectBox queries.
class NotebookModel_ {
  /// See [NotebookModel.id].
  static final id = obx.QueryIntegerProperty<NotebookModel>(
    _entities[4].properties[0],
  );

  /// See [NotebookModel.title].
  static final title = obx.QueryStringProperty<NotebookModel>(
    _entities[4].properties[1],
  );

  /// See [NotebookModel.description].
  static final description = obx.QueryStringProperty<NotebookModel>(
    _entities[4].properties[2],
  );

  /// See [NotebookModel.color].
  static final color = obx.QueryStringProperty<NotebookModel>(
    _entities[4].properties[3],
  );

  /// See [NotebookModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<NotebookModel>(
    _entities[4].properties[4],
  );

  /// See [NotebookModel.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<NotebookModel>(
    _entities[4].properties[5],
  );
}

/// [QuizAttemptModel] entity fields to define ObjectBox queries.
class QuizAttemptModel_ {
  /// See [QuizAttemptModel.id].
  static final id = obx.QueryIntegerProperty<QuizAttemptModel>(
    _entities[5].properties[0],
  );

  /// See [QuizAttemptModel.quizId].
  static final quizId = obx.QueryIntegerProperty<QuizAttemptModel>(
    _entities[5].properties[1],
  );

  /// See [QuizAttemptModel.score].
  static final score = obx.QueryIntegerProperty<QuizAttemptModel>(
    _entities[5].properties[2],
  );

  /// See [QuizAttemptModel.totalQuestions].
  static final totalQuestions = obx.QueryIntegerProperty<QuizAttemptModel>(
    _entities[5].properties[3],
  );

  /// See [QuizAttemptModel.answersJson].
  static final answersJson = obx.QueryStringProperty<QuizAttemptModel>(
    _entities[5].properties[4],
  );

  /// See [QuizAttemptModel.completedAt].
  static final completedAt = obx.QueryDateNanoProperty<QuizAttemptModel>(
    _entities[5].properties[5],
  );
}

/// [QuizModel] entity fields to define ObjectBox queries.
class QuizModel_ {
  /// See [QuizModel.id].
  static final id = obx.QueryIntegerProperty<QuizModel>(
    _entities[6].properties[0],
  );

  /// See [QuizModel.notebookId].
  static final notebookId = obx.QueryIntegerProperty<QuizModel>(
    _entities[6].properties[1],
  );

  /// See [QuizModel.title].
  static final title = obx.QueryStringProperty<QuizModel>(
    _entities[6].properties[2],
  );

  /// See [QuizModel.questionTypeStr].
  static final questionTypeStr = obx.QueryStringProperty<QuizModel>(
    _entities[6].properties[3],
  );

  /// See [QuizModel.difficultyStr].
  static final difficultyStr = obx.QueryStringProperty<QuizModel>(
    _entities[6].properties[4],
  );

  /// See [QuizModel.questionCount].
  static final questionCount = obx.QueryIntegerProperty<QuizModel>(
    _entities[6].properties[5],
  );

  /// See [QuizModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<QuizModel>(
    _entities[6].properties[6],
  );
}

/// [QuizQuestionModel] entity fields to define ObjectBox queries.
class QuizQuestionModel_ {
  /// See [QuizQuestionModel.id].
  static final id = obx.QueryIntegerProperty<QuizQuestionModel>(
    _entities[7].properties[0],
  );

  /// See [QuizQuestionModel.quizId].
  static final quizId = obx.QueryIntegerProperty<QuizQuestionModel>(
    _entities[7].properties[1],
  );

  /// See [QuizQuestionModel.question].
  static final question = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[2],
  );

  /// See [QuizQuestionModel.typeStr].
  static final typeStr = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[3],
  );

  /// See [QuizQuestionModel.optionsJson].
  static final optionsJson = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[4],
  );

  /// See [QuizQuestionModel.correctAnswer].
  static final correctAnswer = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[5],
  );

  /// See [QuizQuestionModel.explanation].
  static final explanation = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[6],
  );

  /// See [QuizQuestionModel.questionIndex].
  static final questionIndex = obx.QueryIntegerProperty<QuizQuestionModel>(
    _entities[7].properties[7],
  );

  /// See [QuizQuestionModel.options].
  static final options = obx.QueryStringVectorProperty<QuizQuestionModel>(
    _entities[7].properties[8],
  );

  /// See [QuizQuestionModel.topic].
  static final topic = obx.QueryStringProperty<QuizQuestionModel>(
    _entities[7].properties[9],
  );
}

/// [FlashcardDeckModel] entity fields to define ObjectBox queries.
class FlashcardDeckModel_ {
  /// See [FlashcardDeckModel.id].
  static final id = obx.QueryIntegerProperty<FlashcardDeckModel>(
    _entities[8].properties[0],
  );

  /// See [FlashcardDeckModel.notebookId].
  static final notebookId = obx.QueryIntegerProperty<FlashcardDeckModel>(
    _entities[8].properties[1],
  );

  /// See [FlashcardDeckModel.title].
  static final title = obx.QueryStringProperty<FlashcardDeckModel>(
    _entities[8].properties[2],
  );

  /// See [FlashcardDeckModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<FlashcardDeckModel>(
    _entities[8].properties[3],
  );

  /// See [FlashcardDeckModel.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<FlashcardDeckModel>(
    _entities[8].properties[4],
  );
}

/// [FlashcardModel] entity fields to define ObjectBox queries.
class FlashcardModel_ {
  /// See [FlashcardModel.id].
  static final id = obx.QueryIntegerProperty<FlashcardModel>(
    _entities[9].properties[0],
  );

  /// See [FlashcardModel.deckId].
  static final deckId = obx.QueryIntegerProperty<FlashcardModel>(
    _entities[9].properties[1],
  );

  /// See [FlashcardModel.front].
  static final front = obx.QueryStringProperty<FlashcardModel>(
    _entities[9].properties[2],
  );

  /// See [FlashcardModel.back].
  static final back = obx.QueryStringProperty<FlashcardModel>(
    _entities[9].properties[3],
  );

  /// See [FlashcardModel.cardIndex].
  static final cardIndex = obx.QueryIntegerProperty<FlashcardModel>(
    _entities[9].properties[4],
  );

  /// See [FlashcardModel.easeFactor].
  static final easeFactor = obx.QueryDoubleProperty<FlashcardModel>(
    _entities[9].properties[5],
  );

  /// See [FlashcardModel.interval].
  static final interval = obx.QueryIntegerProperty<FlashcardModel>(
    _entities[9].properties[6],
  );

  /// See [FlashcardModel.repetitions].
  static final repetitions = obx.QueryIntegerProperty<FlashcardModel>(
    _entities[9].properties[7],
  );

  /// See [FlashcardModel.nextReviewAt].
  static final nextReviewAt = obx.QueryDateNanoProperty<FlashcardModel>(
    _entities[9].properties[8],
  );

  /// See [FlashcardModel.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<FlashcardModel>(
    _entities[9].properties[9],
  );
}

/// [FlashcardReviewModel] entity fields to define ObjectBox queries.
class FlashcardReviewModel_ {
  /// See [FlashcardReviewModel.id].
  static final id = obx.QueryIntegerProperty<FlashcardReviewModel>(
    _entities[10].properties[0],
  );

  /// See [FlashcardReviewModel.flashcardId].
  static final flashcardId = obx.QueryIntegerProperty<FlashcardReviewModel>(
    _entities[10].properties[1],
  );

  /// See [FlashcardReviewModel.quality].
  static final quality = obx.QueryIntegerProperty<FlashcardReviewModel>(
    _entities[10].properties[2],
  );

  /// See [FlashcardReviewModel.reviewedAt].
  static final reviewedAt = obx.QueryDateNanoProperty<FlashcardReviewModel>(
    _entities[10].properties[3],
  );
}

/// [StudyPlanModel] entity fields to define ObjectBox queries.
class StudyPlanModel_ {
  /// See [StudyPlanModel.id].
  static final id = obx.QueryIntegerProperty<StudyPlanModel>(
    _entities[11].properties[0],
  );

  /// See [StudyPlanModel.date].
  static final date = obx.QueryDateNanoProperty<StudyPlanModel>(
    _entities[11].properties[1],
  );

  /// See [StudyPlanModel.tasksJson].
  static final tasksJson = obx.QueryStringProperty<StudyPlanModel>(
    _entities[11].properties[2],
  );

  /// See [StudyPlanModel.generatedAt].
  static final generatedAt = obx.QueryDateNanoProperty<StudyPlanModel>(
    _entities[11].properties[3],
  );
}

/// [StudySessionModel] entity fields to define ObjectBox queries.
class StudySessionModel_ {
  /// See [StudySessionModel.id].
  static final id = obx.QueryIntegerProperty<StudySessionModel>(
    _entities[12].properties[0],
  );

  /// See [StudySessionModel.notebookId].
  static final notebookId = obx.QueryIntegerProperty<StudySessionModel>(
    _entities[12].properties[1],
  );

  /// See [StudySessionModel.activityType].
  static final activityType = obx.QueryStringProperty<StudySessionModel>(
    _entities[12].properties[2],
  );

  /// See [StudySessionModel.durationSeconds].
  static final durationSeconds = obx.QueryIntegerProperty<StudySessionModel>(
    _entities[12].properties[3],
  );

  /// See [StudySessionModel.startedAt].
  static final startedAt = obx.QueryDateNanoProperty<StudySessionModel>(
    _entities[12].properties[4],
  );

  /// See [StudySessionModel.endedAt].
  static final endedAt = obx.QueryDateNanoProperty<StudySessionModel>(
    _entities[12].properties[5],
  );
}

/// [HighlightModel] entity fields to define ObjectBox queries.
class HighlightModel_ {
  /// See [HighlightModel.id].
  static final id = obx.QueryIntegerProperty<HighlightModel>(
    _entities[13].properties[0],
  );

  /// See [HighlightModel.noteId].
  static final noteId = obx.QueryIntegerProperty<HighlightModel>(
    _entities[13].properties[1],
  );

  /// See [HighlightModel.text].
  static final text = obx.QueryStringProperty<HighlightModel>(
    _entities[13].properties[2],
  );

  /// See [HighlightModel.colorValue].
  static final colorValue = obx.QueryIntegerProperty<HighlightModel>(
    _entities[13].properties[3],
  );

  /// See [HighlightModel.note].
  static final note = obx.QueryStringProperty<HighlightModel>(
    _entities[13].properties[4],
  );

  /// See [HighlightModel.createdAt].
  static final createdAt = obx.QueryDateProperty<HighlightModel>(
    _entities[13].properties[5],
  );

  /// See [HighlightModel.aiAnswer].
  static final aiAnswer = obx.QueryStringProperty<HighlightModel>(
    _entities[13].properties[6],
  );
}

/// [NoteAnnotationModel] entity fields to define ObjectBox queries.
class NoteAnnotationModel_ {
  /// See [NoteAnnotationModel.id].
  static final id = obx.QueryIntegerProperty<NoteAnnotationModel>(
    _entities[14].properties[0],
  );

  /// See [NoteAnnotationModel.noteId].
  static final noteId = obx.QueryIntegerProperty<NoteAnnotationModel>(
    _entities[14].properties[1],
  );

  /// See [NoteAnnotationModel.strokesJson].
  static final strokesJson = obx.QueryStringProperty<NoteAnnotationModel>(
    _entities[14].properties[2],
  );

  /// See [NoteAnnotationModel.sidenotesJson].
  static final sidenotesJson = obx.QueryStringProperty<NoteAnnotationModel>(
    _entities[14].properties[3],
  );

  /// See [NoteAnnotationModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<NoteAnnotationModel>(
    _entities[14].properties[4],
  );
}
